#s = input()
n = int(input())
a, b = list(map(int, input().split()))
#a, b = input().split()
#a, b, c = map(int, input().split())
#a, b, c = input().split()
#a = map(int, input().split())
#a = input().split()

#t = input()
m = int(input())
#p, q = map(int, input().split())
#p, q = input().split()
#p, q, r = map(int, input().split())
#p, q, r = input().split()
p = list(map(int, input().split()))
#b = input().split()
print("YES" if len(p) == len(set(p)) and a not in p and b not in p else "NO")
